export type ToneTag = {
  event: string
  feeling: string
  key: string
}

/** Most-used Gemini TTS / performance tags, ordered by common worldwide use. */
export const TONE_TAGS: ToneTag[] = [
  { event: "آرام در گوش می‌گوید", feeling: "محرمانه، صمیمی، نزدیک", key: "{whispers}" },
  { event: "با صدای بلند فریاد می‌زند", feeling: "خشم، هیجان شدید، هشدار", key: "{shouting}" },
  { event: "می‌خندد", feeling: "شادی، شوخی، سبکی", key: "{laughs}" },
  { event: "آه می‌کشد", feeling: "خستگی، رهایی، ناامیدی ملایم", key: "{sighs}" },
  { event: "نفسش بند می‌آید", feeling: "شوک، ترس ناگهانی، شگفتی", key: "{gasp}" },
  { event: "با هیجان حرف می‌زند", feeling: "شوق، انرژی، اشتیاق", key: "{excited}" },
  { event: "با هیجان و سرزندگی می‌گوید", feeling: "ذوق‌زدگی، خوشحالی فعال", key: "{excitedly}" },
  { event: "کسل و بی‌حوصله می‌خواند", feeling: "ملال، بی‌علاقگی", key: "{bored}" },
  { event: "با اکراه حرف می‌زند", feeling: "بی‌میلی، تردید", key: "{reluctantly}" },
  { event: "خیلی تند حرف می‌زند", feeling: "عجله، اضطراب، انرژی بالا", key: "{very fast}" },
  { event: "خیلی آهسته حرف می‌زند", feeling: "تأکید، سنگینی، آرامش عمیق", key: "{very slow}" },
  { event: "طعنه‌آمیز حرف می‌زند", feeling: "تمسخر مؤدبانه، کنایه", key: "{sarcastic}" },
  { event: "با لحن کنایه‌دار می‌گوید", feeling: "نیشخند، فاصله گرفتن از حرف", key: "{sarcastically}" },
  { event: "گریه می‌کند", feeling: "غم، شکست، دل‌شکستگی", key: "{crying}" },
  { event: "کنجکاوانه می‌پرسد یا می‌گوید", feeling: "پرسش، توجه، کشف", key: "{curious}" },
  { event: "با حیرت حرف می‌زند", feeling: "شگفتی، بهت", key: "{amazed}" },
  { event: "می‌خنددِ ریز و بازیگوش", feeling: "شرم شیرین، شیطنت ملایم", key: "{giggles}" },
  { event: "با شیطنت حرف می‌زند", feeling: "بازیگوشی، فتنهٔ دوستانه", key: "{mischievously}" },
  { event: "هراسان و شتاب‌زده می‌گوید", feeling: "اضطراب شدید، ترس", key: "{panicked}" },
  { event: "جدی و رسمی می‌گوید", feeling: "اهمیت، تمرکز، سنگینی موضوع", key: "{serious}" },
  { event: "خسته حرف می‌زند", feeling: "فرسودگی، کم‌رمقی", key: "{tired}" },
  { event: "صدایش می‌لرزد", feeling: "ترس، ضعف، احساسات شدید", key: "{trembling}" },
  { event: "سرفه می‌کند", feeling: "وقفه، ناراحتی جسمی، جمع کردن خود", key: "{cough}" },
  { event: "مکث کوتاه می‌کند", feeling: "تنفس، تأکید، فاصله بین جمله‌ها", key: "{short pause}" },
  { event: "مکث بلند می‌کند", feeling: "درام، فکر کردن، سکوت معنا‌دار", key: "{long pause}" },
  { event: "مکث می‌کند", feeling: "وقفه طبیعی در گفتار", key: "{pause}" },
  { event: "عصبانی حرف می‌زند", feeling: "خشم، اعتراض", key: "{angry}" },
  { event: "با خشم می‌گوید", feeling: "تندخویی، فشار احساسی", key: "{angrily}" },
  { event: "غمگین حرف می‌زند", feeling: "اندوه، دل‌گرفتگی", key: "{sad}" },
  { event: "با ناراحتی می‌گوید", feeling: "غم ملایم، دلسردی", key: "{sadly}" },
  { event: "خوشحال حرف می‌زند", feeling: "شادمانی، گرمی", key: "{happy}" },
  { event: "با خوشحالی می‌گوید", feeling: "سرزندگی، رضایت", key: "{happily}" },
  { event: "آرام و مسلط حرف می‌زند", feeling: "اطمینان، سکون", key: "{calm}" },
  { event: "با لحنی گرم می‌گوید", feeling: "مهربانی، صمیمیت", key: "{warm}" },
  { event: "آرام و نرم می‌گوید", feeling: "لطافت، مراقبت", key: "{softly}" },
  { event: "بلند و رسا می‌گوید", feeling: "قدرت، اعلام، حضور", key: "{loudly}" },
  { event: "با لبخند در صدا حرف می‌زند", feeling: "دوستانه بودن، دعوت", key: "{cheerfully}" },
  { event: "با اطمینان حرف می‌زند", feeling: "اعتمادبه‌نفس، ثبات", key: "{confident}" },
  { event: "مضطرب حرف می‌زند", feeling: "نگرانی، بی‌قراری", key: "{nervous}" },
  { event: "نمایشی و پررنگ می‌گوید", feeling: "تئاتر، برجسته‌سازی", key: "{dramatic}" },
  { event: "با مهربانی می‌گوید", feeling: "شفقت، نرمی", key: "{gently}" },
  { event: "محکم و قاطع می‌گوید", feeling: "تصمیم، اقتدار", key: "{firmly}" },
  { event: "ناامید حرف می‌زند", feeling: "سرخوردگی، انتظار برآورده‌نشده", key: "{disappointed}" },
  { event: "با امید حرف می‌زند", feeling: "انتظار مثبت، دلگرمی", key: "{hopeful}" },
  { event: "ترسیده حرف می‌زند", feeling: "هراس، احتیاط", key: "{fearful}" },
  { event: "با افتخار می‌گوید", feeling: "غرور سالم، پیروزی", key: "{proud}" },
  { event: "گیج حرف می‌زند", feeling: "سردرگمی، نفهمیدن", key: "{confused}" },
  { event: "خشک و بی‌احساس می‌گوید", feeling: "کنایه سرد، فاصله", key: "{deadpan}" },
  { event: "با اشتیاق زیاد حرف می‌زند", feeling: "انرژی بالا، انگیزه", key: "{enthusiastic}" },
  { event: "زیرلب حرف می‌زند", feeling: "پنهان‌کاری، فکر خصوصی", key: "{muttering}" },
  { event: "خمیازه می‌کشد", feeling: "خواب‌آلودگی، بی‌حوصلگی", key: "{yawn}" },
  { event: "هق‌هق می‌کند", feeling: "غم سنگین، شکستن صدا", key: "{sobbing}" },
  { event: "با صدای گرفته گریه می‌کند", feeling: "اشک فروخورده، ضعف", key: "{teary}" },
  { event: "بازیگوش حرف می‌زند", feeling: "شوخی، سبکی کودکانه", key: "{playfully}" },
  { event: "با نفس‌بریدگی می‌گوید", feeling: "عجله، هیجان بدنی", key: "{breathlessly}" },
  { event: "گلویش را صاف می‌کند", feeling: "آماده‌شدن، جلب توجه", key: "{clears throat}" },
  { event: "کلمه به کلمه و آهسته می‌گوید", feeling: "تأکید آزارنده یا دقیق", key: "{one word at a time}" },
  { event: "با تردید حرف می‌زند", feeling: "دو دلی، ناباوری ملایم", key: "{hesitant}" },
  { event: "با خشم انفجاری می‌گوید", feeling: "غضب، از کوره در رفتن", key: "{furious}" },
  { event: "با شادی زیاد می‌گوید", feeling: "شعف، ذوق", key: "{delighted}" },
  { event: "با شک و ناباوری می‌گوید", feeling: "تردید، سؤال‌برانگیزی", key: "{skeptical}" },
  { event: "با نرمی عاطفی حرف می‌زند", feeling: "عشق، مراقبت نزدیک", key: "{tender}" },
  { event: "تهدیدآمیز حرف می‌زند", feeling: "ترس‌آفرینی، قدرت تاریک", key: "{menacing}" },
  { event: "زیرلب و آهسته مثل نجوا می‌گوید", feeling: "راز، نزدیکی به میکروفون", key: "{under breath}" },
  { event: "با صدای یکنواخت می‌خواند", feeling: "بی‌احساسی، خستگی یا رسمیت خشک", key: "{monotone}" },
  { event: "با عجله قورت‌داده‌وار می‌گوید", feeling: "شتاب، فشار زمان", key: "{rushed}" },
]
